// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vrulcqoxhbvlkvkdiisv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZydWxjcW94aGJ2bGt2a2RpaXN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNzcwMzcsImV4cCI6MjA2OTY1MzAzN30.O1noXVfHtGmxXZkGsy66Tv-vPD5KaCQColSKmZ5FY-E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});